github:
  description: "Apache Spark Connect for Rust"
  homepage: "https://spark.apache.org/"
  labels:
    - spark
    - rust
    - spark-connect
    - data
    - distributed

  enabled_merge_buttons:
    merge: false
    squash: true
    rebase: true

  features:
    issues: true
    projects: true

  ghp_branch: gh-pages
  ghp_path: /

  autolink_jira: SPARK

  rulesets:
    - name: "Default Branch Protection"
      type: branch
      branches:
        includes:
          - "~DEFAULT_BRANCH"
          - "release/*"
          - "rel/*"
        excludes: []
      bypass_teams:
        - root
      restrict_deletion: true
      restrict_force_push: true
notifications:
  pullrequests: reviews@spark.apache.org
  issues: reviews@spark.apache.org
  commits: commits@spark.apache.org
  jira_options: link label
