// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

//! Single-file Rust UDF on Spark: define the function and use it in one file.
//!
//! `build.rs` compiles this same file to a `wasm32` module (host-only code is
//! `#[cfg(not(target_arch = "wasm32"))]`, so only the exported UDF survives) and
//! embeds it; `#[spark_wasm_udf]` generates the `add_one_udf()` constructor.
//!
//! Run (needs the wasm32 target + a Spark Connect server, `wasmtime` on the
//! executors):
//!
//!     rustup target add wasm32-unknown-unknown
//!     export SPARK_CONNECT_WASM_PACKER_PATH=$PWD/python
//!     cargo run -p wasm-udf-inline

use spark_connect_macros::spark_wasm_udf;

/// The UDF — a plain Rust function. That's all the user writes.
#[spark_wasm_udf]
pub fn add_one(x: i64) -> i64 {
    x + 1
}

#[cfg(not(target_arch = "wasm32"))]
fn main() -> Result<(), Box<dyn std::error::Error>> {
    use spark_connect::functions::col;
    use spark_connect::{SparkSession, SparkSessionBuilder};

    let spark: SparkSession = SparkSessionBuilder::default()
        .remote("sc://127.0.0.1:15002/")
        .get_or_create()?;

    // `add_one_udf()` is generated by the macro: signature inferred, module
    // embedded. No wasm bytes or signature to write by hand.
    spark
        .range(5)?
        .select(vec![
            col("id"),
            add_one_udf().call(vec![col("id")])?.alias("id_plus_one"),
        ])
        .show(20)?;

    Ok(())
}
