//! Auto-generated coverage smoke test - do not edit directly.
//! Generated by scripts/gen_functions_coverage_test.py.
//!
//! Constructs every public `functions.*` builder with canonical arguments and
//! serializes it to protobuf, so the coverage gate exercises every builder body.
//! Correctness/parity is covered by `functions_golden.rs`; this only guards that
//! no builder panics or is left untested. 551 builders exercised;
//! 5 skipped (non-canonical signatures): broadcast, from_protobuf_with_descriptor, from_protobuf_with_descriptor_and_options, to_protobuf_with_descriptor, to_protobuf_with_descriptor_and_options.

use prost::Message;
use spark_connect::column::Column;
use spark_connect::expression::{ColumnReference, Expression};
use spark_connect::functions as spark_funcs;

/// A canonical column reference argument.
fn c() -> Column {
    Column::new(Expression::ColumnReference(ColumnReference::new("c")))
}

#[test]
fn every_function_builder_serializes() {
    let _ = spark_funcs::col("x").to_proto().encode_to_vec();
    let _ = spark_funcs::column("x").to_proto().encode_to_vec();
    let _ = spark_funcs::lit(c()).to_proto().encode_to_vec();
    let _ = spark_funcs::expr("x").to_proto().encode_to_vec();
    let _ = spark_funcs::cast(c(), c()).to_proto().encode_to_vec();
    let _ = spark_funcs::call_function("x").to_proto().encode_to_vec();
    let _ = spark_funcs::call_udf("x").to_proto().encode_to_vec();
    let _ = spark_funcs::asc(c()).to_proto().encode_to_vec();
    let _ = spark_funcs::asc_nulls_first(c()).to_proto().encode_to_vec();
    let _ = spark_funcs::asc_nulls_last(c()).to_proto().encode_to_vec();
    let _ = spark_funcs::desc(c()).to_proto().encode_to_vec();
    let _ = spark_funcs::desc_nulls_first(c())
        .to_proto()
        .encode_to_vec();
    let _ = spark_funcs::desc_nulls_last(c()).to_proto().encode_to_vec();
    let _ = spark_funcs::array(vec![c(), c()])
        .to_proto()
        .encode_to_vec();
    let _ = spark_funcs::concat(vec![c(), c()])
        .to_proto()
        .encode_to_vec();
    let _ = spark_funcs::coalesce(vec![c(), c()])
        .to_proto()
        .encode_to_vec();
    let _ = spark_funcs::arrays_zip(vec![c(), c()])
        .to_proto()
        .encode_to_vec();
    let _ = spark_funcs::create_map(vec![c(), c()])
        .to_proto()
        .encode_to_vec();
    let _ = spark_funcs::window(c(), "x").to_proto().encode_to_vec();
    let _ = spark_funcs::window_with_slide_and_start(c(), "x", "x", "x")
        .to_proto()
        .encode_to_vec();
    let _ = spark_funcs::curdate().to_proto().encode_to_vec();
    let _ = spark_funcs::current_catalog().to_proto().encode_to_vec();
    let _ = spark_funcs::current_database().to_proto().encode_to_vec();
    let _ = spark_funcs::current_date().to_proto().encode_to_vec();
    let _ = spark_funcs::current_schema().to_proto().encode_to_vec();
    let _ = spark_funcs::current_timestamp().to_proto().encode_to_vec();
    let _ = spark_funcs::current_timezone().to_proto().encode_to_vec();
    let _ = spark_funcs::current_user().to_proto().encode_to_vec();
    let _ = spark_funcs::dense_rank().to_proto().encode_to_vec();
    let _ = spark_funcs::e().to_proto().encode_to_vec();
    let _ = spark_funcs::elt(vec![c(), c()]).to_proto().encode_to_vec();
    let _ = spark_funcs::grouping_id(vec![c(), c()])
        .to_proto()
        .encode_to_vec();
    let _ = spark_funcs::hash(vec![c(), c()]).to_proto().encode_to_vec();
    let _ = spark_funcs::input_file_block_length()
        .to_proto()
        .encode_to_vec();
    let _ = spark_funcs::input_file_block_start()
        .to_proto()
        .encode_to_vec();
    let _ = spark_funcs::input_file_name().to_proto().encode_to_vec();
    let _ = spark_funcs::java_method(vec![c(), c()])
        .to_proto()
        .encode_to_vec();
    let _ = spark_funcs::localtimestamp().to_proto().encode_to_vec();
    let _ = spark_funcs::make_dt_interval().to_proto().encode_to_vec();
    let _ = spark_funcs::make_interval().to_proto().encode_to_vec();
    let _ = spark_funcs::make_ym_interval().to_proto().encode_to_vec();
    let _ = spark_funcs::map_concat(vec![c(), c()])
        .to_proto()
        .encode_to_vec();
    let _ = spark_funcs::monotonically_increasing_id()
        .to_proto()
        .encode_to_vec();
    let _ = spark_funcs::named_struct(vec![c(), c()])
        .to_proto()
        .encode_to_vec();
    let _ = spark_funcs::now().to_proto().encode_to_vec();
    let _ = spark_funcs::percent_rank().to_proto().encode_to_vec();
    let _ = spark_funcs::pi().to_proto().encode_to_vec();
    let _ = spark_funcs::rand().to_proto().encode_to_vec();
    let _ = spark_funcs::randn().to_proto().encode_to_vec();
    let _ = spark_funcs::rank().to_proto().encode_to_vec();
    let _ = spark_funcs::reflect(vec![c(), c()])
        .to_proto()
        .encode_to_vec();
    let _ = spark_funcs::row_number().to_proto().encode_to_vec();
    let _ = spark_funcs::session_user().to_proto().encode_to_vec();
    let _ = spark_funcs::spark_partition_id().to_proto().encode_to_vec();
    let _ = spark_funcs::stack(vec![c(), c()])
        .to_proto()
        .encode_to_vec();
    let _ = spark_funcs::r#struct(vec![c(), c()])
        .to_proto()
        .encode_to_vec();
    let _ = spark_funcs::try_make_interval().to_proto().encode_to_vec();
    let _ = spark_funcs::try_reflect(vec![c(), c()])
        .to_proto()
        .encode_to_vec();
    let _ = spark_funcs::unix_timestamp().to_proto().encode_to_vec();
    let _ = spark_funcs::user().to_proto().encode_to_vec();
    let _ = spark_funcs::version().to_proto().encode_to_vec();
    let _ = spark_funcs::xxhash64(vec![c(), c()])
        .to_proto()
        .encode_to_vec();
    let _ = spark_funcs::abs(c()).to_proto().encode_to_vec();
    let _ = spark_funcs::acos(c()).to_proto().encode_to_vec();
    let _ = spark_funcs::acosh(c()).to_proto().encode_to_vec();
    let _ = spark_funcs::any_value(c()).to_proto().encode_to_vec();
    let _ = spark_funcs::approxCountDistinct(c())
        .to_proto()
        .encode_to_vec();
    let _ = spark_funcs::approx_count_distinct(c())
        .to_proto()
        .encode_to_vec();
    let _ = spark_funcs::array_agg(c()).to_proto().encode_to_vec();
    let _ = spark_funcs::array_compact(c()).to_proto().encode_to_vec();
    let _ = spark_funcs::array_distinct(c()).to_proto().encode_to_vec();
    let _ = spark_funcs::array_max(c()).to_proto().encode_to_vec();
    let _ = spark_funcs::array_min(c()).to_proto().encode_to_vec();
    let _ = spark_funcs::array_size(c()).to_proto().encode_to_vec();
    let _ = spark_funcs::array_sort(c()).to_proto().encode_to_vec();
    let _ = spark_funcs::ascii(c()).to_proto().encode_to_vec();
    let _ = spark_funcs::asin(c()).to_proto().encode_to_vec();
    let _ = spark_funcs::asinh(c()).to_proto().encode_to_vec();
    let _ = spark_funcs::assert_true(c()).to_proto().encode_to_vec();
    let _ = spark_funcs::atan(c()).to_proto().encode_to_vec();
    let _ = spark_funcs::atanh(c()).to_proto().encode_to_vec();
    let _ = spark_funcs::avg(c()).to_proto().encode_to_vec();
    let _ = spark_funcs::base64(c()).to_proto().encode_to_vec();
    let _ = spark_funcs::bin(c()).to_proto().encode_to_vec();
    let _ = spark_funcs::bit_and(c()).to_proto().encode_to_vec();
    let _ = spark_funcs::bit_count(c()).to_proto().encode_to_vec();
    let _ = spark_funcs::bit_length(c()).to_proto().encode_to_vec();
    let _ = spark_funcs::bit_or(c()).to_proto().encode_to_vec();
    let _ = spark_funcs::bit_xor(c()).to_proto().encode_to_vec();
    let _ = spark_funcs::bitmap_bit_position(c())
        .to_proto()
        .encode_to_vec();
    let _ = spark_funcs::bitmap_bucket_number(c())
        .to_proto()
        .encode_to_vec();
    let _ = spark_funcs::bitmap_construct_agg(c())
        .to_proto()
        .encode_to_vec();
    let _ = spark_funcs::bitmap_count(c()).to_proto().encode_to_vec();
    let _ = spark_funcs::bitmap_or_agg(c()).to_proto().encode_to_vec();
    let _ = spark_funcs::bitwiseNOT(c()).to_proto().encode_to_vec();
    let _ = spark_funcs::bitwise_not(c()).to_proto().encode_to_vec();
    let _ = spark_funcs::bool_and(c()).to_proto().encode_to_vec();
    let _ = spark_funcs::bool_or(c()).to_proto().encode_to_vec();
    let _ = spark_funcs::bround(c()).to_proto().encode_to_vec();
    let _ = spark_funcs::btrim(c()).to_proto().encode_to_vec();
    let _ = spark_funcs::cardinality(c()).to_proto().encode_to_vec();
    let _ = spark_funcs::cbrt(c()).to_proto().encode_to_vec();
    let _ = spark_funcs::ceil(c()).to_proto().encode_to_vec();
    let _ = spark_funcs::ceiling(c()).to_proto().encode_to_vec();
    let _ = spark_funcs::char(c()).to_proto().encode_to_vec();
    let _ = spark_funcs::char_length(c()).to_proto().encode_to_vec();
    let _ = spark_funcs::character_length(c())
        .to_proto()
        .encode_to_vec();
    let _ = spark_funcs::collation(c()).to_proto().encode_to_vec();
    let _ = spark_funcs::collect_list(c()).to_proto().encode_to_vec();
    let _ = spark_funcs::collect_set(c()).to_proto().encode_to_vec();
    let _ = spark_funcs::concat_ws(c()).to_proto().encode_to_vec();
    let _ = spark_funcs::cos(c()).to_proto().encode_to_vec();
    let _ = spark_funcs::cosh(c()).to_proto().encode_to_vec();
    let _ = spark_funcs::cot(c()).to_proto().encode_to_vec();
    let _ = spark_funcs::count(c()).to_proto().encode_to_vec();
    let _ = spark_funcs::countDistinct(c()).to_proto().encode_to_vec();
    let _ = spark_funcs::count_distinct(c()).to_proto().encode_to_vec();
    let _ = spark_funcs::count_if(c()).to_proto().encode_to_vec();
    let _ = spark_funcs::crc32(c()).to_proto().encode_to_vec();
    let _ = spark_funcs::csc(c()).to_proto().encode_to_vec();
    let _ = spark_funcs::date_from_unix_date(c())
        .to_proto()
        .encode_to_vec();
    let _ = spark_funcs::day(c()).to_proto().encode_to_vec();
    let _ = spark_funcs::dayname(c()).to_proto().encode_to_vec();
    let _ = spark_funcs::dayofmonth(c()).to_proto().encode_to_vec();
    let _ = spark_funcs::dayofweek(c()).to_proto().encode_to_vec();
    let _ = spark_funcs::dayofyear(c()).to_proto().encode_to_vec();
    let _ = spark_funcs::days(c()).to_proto().encode_to_vec();
    let _ = spark_funcs::degrees(c()).to_proto().encode_to_vec();
    let _ = spark_funcs::every(c()).to_proto().encode_to_vec();
    let _ = spark_funcs::exp(c()).to_proto().encode_to_vec();
    let _ = spark_funcs::explode(c()).to_proto().encode_to_vec();
    let _ = spark_funcs::explode_outer(c()).to_proto().encode_to_vec();
    let _ = spark_funcs::expm1(c()).to_proto().encode_to_vec();
    let _ = spark_funcs::factorial(c()).to_proto().encode_to_vec();
    let _ = spark_funcs::first(c()).to_proto().encode_to_vec();
    let _ = spark_funcs::first_value(c()).to_proto().encode_to_vec();
    let _ = spark_funcs::flatten(c()).to_proto().encode_to_vec();
    let _ = spark_funcs::floor(c()).to_proto().encode_to_vec();
    let _ = spark_funcs::format_string(c()).to_proto().encode_to_vec();
    let _ = spark_funcs::from_unixtime(c()).to_proto().encode_to_vec();
    let _ = spark_funcs::grouping(c()).to_proto().encode_to_vec();
    let _ = spark_funcs::hex(c()).to_proto().encode_to_vec();
    let _ = spark_funcs::hll_sketch_agg(c()).to_proto().encode_to_vec();
    let _ = spark_funcs::hll_sketch_estimate(c())
        .to_proto()
        .encode_to_vec();
    let _ = spark_funcs::hll_union_agg(c()).to_proto().encode_to_vec();
    let _ = spark_funcs::hour(c()).to_proto().encode_to_vec();
    let _ = spark_funcs::hours(c()).to_proto().encode_to_vec();
    let _ = spark_funcs::initcap(c()).to_proto().encode_to_vec();
    let _ = spark_funcs::inline(c()).to_proto().encode_to_vec();
    let _ = spark_funcs::inline_outer(c()).to_proto().encode_to_vec();
    let _ = spark_funcs::is_valid_utf8(c()).to_proto().encode_to_vec();
    let _ = spark_funcs::is_variant_null(c()).to_proto().encode_to_vec();
    let _ = spark_funcs::isnan(c()).to_proto().encode_to_vec();
    let _ = spark_funcs::isnotnull(c()).to_proto().encode_to_vec();
    let _ = spark_funcs::isnull(c()).to_proto().encode_to_vec();
    let _ = spark_funcs::json_array_length(c())
        .to_proto()
        .encode_to_vec();
    let _ = spark_funcs::json_object_keys(c())
        .to_proto()
        .encode_to_vec();
    let _ = spark_funcs::kurtosis(c()).to_proto().encode_to_vec();
    let _ = spark_funcs::lag(c()).to_proto().encode_to_vec();
    let _ = spark_funcs::last(c()).to_proto().encode_to_vec();
    let _ = spark_funcs::last_day(c()).to_proto().encode_to_vec();
    let _ = spark_funcs::last_value(c()).to_proto().encode_to_vec();
    let _ = spark_funcs::lcase(c()).to_proto().encode_to_vec();
    let _ = spark_funcs::lead(c()).to_proto().encode_to_vec();
    let _ = spark_funcs::length(c()).to_proto().encode_to_vec();
    let _ = spark_funcs::listagg(c()).to_proto().encode_to_vec();
    let _ = spark_funcs::listagg_distinct(c())
        .to_proto()
        .encode_to_vec();
    let _ = spark_funcs::ln(c()).to_proto().encode_to_vec();
    let _ = spark_funcs::log(c()).to_proto().encode_to_vec();
    let _ = spark_funcs::log10(c()).to_proto().encode_to_vec();
    let _ = spark_funcs::log1p(c()).to_proto().encode_to_vec();
    let _ = spark_funcs::log2(c()).to_proto().encode_to_vec();
    let _ = spark_funcs::lower(c()).to_proto().encode_to_vec();
    let _ = spark_funcs::ltrim(c()).to_proto().encode_to_vec();
    let _ = spark_funcs::make_valid_utf8(c()).to_proto().encode_to_vec();
    let _ = spark_funcs::map_entries(c()).to_proto().encode_to_vec();
    let _ = spark_funcs::map_from_entries(c())
        .to_proto()
        .encode_to_vec();
    let _ = spark_funcs::map_keys(c()).to_proto().encode_to_vec();
    let _ = spark_funcs::map_values(c()).to_proto().encode_to_vec();
    let _ = spark_funcs::mask(c()).to_proto().encode_to_vec();
    let _ = spark_funcs::max(c()).to_proto().encode_to_vec();
    let _ = spark_funcs::md5(c()).to_proto().encode_to_vec();
    let _ = spark_funcs::mean(c()).to_proto().encode_to_vec();
    let _ = spark_funcs::median(c()).to_proto().encode_to_vec();
    let _ = spark_funcs::min(c()).to_proto().encode_to_vec();
    let _ = spark_funcs::minute(c()).to_proto().encode_to_vec();
    let _ = spark_funcs::mode(c()).to_proto().encode_to_vec();
    let _ = spark_funcs::month(c()).to_proto().encode_to_vec();
    let _ = spark_funcs::monthname(c()).to_proto().encode_to_vec();
    let _ = spark_funcs::months(c()).to_proto().encode_to_vec();
    let _ = spark_funcs::negate(c()).to_proto().encode_to_vec();
    let _ = spark_funcs::negative(c()).to_proto().encode_to_vec();
    let _ = spark_funcs::ntile(c()).to_proto().encode_to_vec();
    let _ = spark_funcs::nullifzero(c()).to_proto().encode_to_vec();
    let _ = spark_funcs::octet_length(c()).to_proto().encode_to_vec();
    let _ = spark_funcs::parse_json(c()).to_proto().encode_to_vec();
    let _ = spark_funcs::posexplode(c()).to_proto().encode_to_vec();
    let _ = spark_funcs::posexplode_outer(c())
        .to_proto()
        .encode_to_vec();
    let _ = spark_funcs::positive(c()).to_proto().encode_to_vec();
    let _ = spark_funcs::printf(c()).to_proto().encode_to_vec();
    let _ = spark_funcs::product(c()).to_proto().encode_to_vec();
    let _ = spark_funcs::quarter(c()).to_proto().encode_to_vec();
    let _ = spark_funcs::radians(c()).to_proto().encode_to_vec();
    let _ = spark_funcs::raise_error(c()).to_proto().encode_to_vec();
    let _ = spark_funcs::randstr(c()).to_proto().encode_to_vec();
    let _ = spark_funcs::reverse(c()).to_proto().encode_to_vec();
    let _ = spark_funcs::rint(c()).to_proto().encode_to_vec();
    let _ = spark_funcs::round(c()).to_proto().encode_to_vec();
    let _ = spark_funcs::rtrim(c()).to_proto().encode_to_vec();
    let _ = spark_funcs::schema_of_csv(c()).to_proto().encode_to_vec();
    let _ = spark_funcs::schema_of_json(c()).to_proto().encode_to_vec();
    let _ = spark_funcs::schema_of_variant(c())
        .to_proto()
        .encode_to_vec();
    let _ = spark_funcs::schema_of_variant_agg(c())
        .to_proto()
        .encode_to_vec();
    let _ = spark_funcs::schema_of_xml(c()).to_proto().encode_to_vec();
    let _ = spark_funcs::sec(c()).to_proto().encode_to_vec();
    let _ = spark_funcs::second(c()).to_proto().encode_to_vec();
    let _ = spark_funcs::sentences(c()).to_proto().encode_to_vec();
    let _ = spark_funcs::sha(c()).to_proto().encode_to_vec();
    let _ = spark_funcs::sha1(c()).to_proto().encode_to_vec();
    let _ = spark_funcs::shuffle(c()).to_proto().encode_to_vec();
    let _ = spark_funcs::sign(c()).to_proto().encode_to_vec();
    let _ = spark_funcs::signum(c()).to_proto().encode_to_vec();
    let _ = spark_funcs::sin(c()).to_proto().encode_to_vec();
    let _ = spark_funcs::sinh(c()).to_proto().encode_to_vec();
    let _ = spark_funcs::size(c()).to_proto().encode_to_vec();
    let _ = spark_funcs::skewness(c()).to_proto().encode_to_vec();
    let _ = spark_funcs::some(c()).to_proto().encode_to_vec();
    let _ = spark_funcs::sort_array(c()).to_proto().encode_to_vec();
    let _ = spark_funcs::soundex(c()).to_proto().encode_to_vec();
    let _ = spark_funcs::sqrt(c()).to_proto().encode_to_vec();
    let _ = spark_funcs::std(c()).to_proto().encode_to_vec();
    let _ = spark_funcs::stddev(c()).to_proto().encode_to_vec();
    let _ = spark_funcs::stddev_pop(c()).to_proto().encode_to_vec();
    let _ = spark_funcs::stddev_samp(c()).to_proto().encode_to_vec();
    let _ = spark_funcs::str_to_map(c()).to_proto().encode_to_vec();
    let _ = spark_funcs::string_agg(c()).to_proto().encode_to_vec();
    let _ = spark_funcs::string_agg_distinct(c())
        .to_proto()
        .encode_to_vec();
    let _ = spark_funcs::sum(c()).to_proto().encode_to_vec();
    let _ = spark_funcs::sumDistinct(c()).to_proto().encode_to_vec();
    let _ = spark_funcs::sum_distinct(c()).to_proto().encode_to_vec();
    let _ = spark_funcs::tan(c()).to_proto().encode_to_vec();
    let _ = spark_funcs::tanh(c()).to_proto().encode_to_vec();
    let _ = spark_funcs::timestamp_micros(c())
        .to_proto()
        .encode_to_vec();
    let _ = spark_funcs::timestamp_millis(c())
        .to_proto()
        .encode_to_vec();
    let _ = spark_funcs::timestamp_seconds(c())
        .to_proto()
        .encode_to_vec();
    let _ = spark_funcs::toDegrees(c()).to_proto().encode_to_vec();
    let _ = spark_funcs::toRadians(c()).to_proto().encode_to_vec();
    let _ = spark_funcs::to_binary(c()).to_proto().encode_to_vec();
    let _ = spark_funcs::to_csv(c()).to_proto().encode_to_vec();
    let _ = spark_funcs::to_date(c()).to_proto().encode_to_vec();
    let _ = spark_funcs::to_json(c()).to_proto().encode_to_vec();
    let _ = spark_funcs::to_timestamp(c()).to_proto().encode_to_vec();
    let _ = spark_funcs::to_timestamp_ltz(c())
        .to_proto()
        .encode_to_vec();
    let _ = spark_funcs::to_timestamp_ntz(c())
        .to_proto()
        .encode_to_vec();
    let _ = spark_funcs::to_unix_timestamp(c())
        .to_proto()
        .encode_to_vec();
    let _ = spark_funcs::to_variant_object(c())
        .to_proto()
        .encode_to_vec();
    let _ = spark_funcs::to_xml(c()).to_proto().encode_to_vec();
    let _ = spark_funcs::trim(c()).to_proto().encode_to_vec();
    let _ = spark_funcs::try_avg(c()).to_proto().encode_to_vec();
    let _ = spark_funcs::try_parse_json(c()).to_proto().encode_to_vec();
    let _ = spark_funcs::try_sum(c()).to_proto().encode_to_vec();
    let _ = spark_funcs::try_to_binary(c()).to_proto().encode_to_vec();
    let _ = spark_funcs::try_to_timestamp(c())
        .to_proto()
        .encode_to_vec();
    let _ = spark_funcs::try_url_decode(c()).to_proto().encode_to_vec();
    let _ = spark_funcs::try_validate_utf8(c())
        .to_proto()
        .encode_to_vec();
    let _ = spark_funcs::r#typeof(c()).to_proto().encode_to_vec();
    let _ = spark_funcs::ucase(c()).to_proto().encode_to_vec();
    let _ = spark_funcs::unbase64(c()).to_proto().encode_to_vec();
    let _ = spark_funcs::unhex(c()).to_proto().encode_to_vec();
    let _ = spark_funcs::unix_date(c()).to_proto().encode_to_vec();
    let _ = spark_funcs::unix_micros(c()).to_proto().encode_to_vec();
    let _ = spark_funcs::unix_millis(c()).to_proto().encode_to_vec();
    let _ = spark_funcs::unix_seconds(c()).to_proto().encode_to_vec();
    let _ = spark_funcs::unwrap_udt(c()).to_proto().encode_to_vec();
    let _ = spark_funcs::upper(c()).to_proto().encode_to_vec();
    let _ = spark_funcs::url_decode(c()).to_proto().encode_to_vec();
    let _ = spark_funcs::url_encode(c()).to_proto().encode_to_vec();
    let _ = spark_funcs::validate_utf8(c()).to_proto().encode_to_vec();
    let _ = spark_funcs::var_pop(c()).to_proto().encode_to_vec();
    let _ = spark_funcs::var_samp(c()).to_proto().encode_to_vec();
    let _ = spark_funcs::variance(c()).to_proto().encode_to_vec();
    let _ = spark_funcs::weekday(c()).to_proto().encode_to_vec();
    let _ = spark_funcs::weekofyear(c()).to_proto().encode_to_vec();
    let _ = spark_funcs::window_time(c()).to_proto().encode_to_vec();
    let _ = spark_funcs::year(c()).to_proto().encode_to_vec();
    let _ = spark_funcs::years(c()).to_proto().encode_to_vec();
    let _ = spark_funcs::zeroifnull(c()).to_proto().encode_to_vec();
    let _ = spark_funcs::add_months(c(), c()).to_proto().encode_to_vec();
    let _ = spark_funcs::aes_decrypt(c(), c())
        .to_proto()
        .encode_to_vec();
    let _ = spark_funcs::aes_encrypt(c(), c())
        .to_proto()
        .encode_to_vec();
    let _ = spark_funcs::approx_percentile(c(), c())
        .to_proto()
        .encode_to_vec();
    let _ = spark_funcs::array_append(c(), c())
        .to_proto()
        .encode_to_vec();
    let _ = spark_funcs::array_contains(c(), c())
        .to_proto()
        .encode_to_vec();
    let _ = spark_funcs::array_except(c(), c())
        .to_proto()
        .encode_to_vec();
    let _ = spark_funcs::array_intersect(c(), c())
        .to_proto()
        .encode_to_vec();
    let _ = spark_funcs::array_join(c(), c()).to_proto().encode_to_vec();
    let _ = spark_funcs::array_position(c(), c())
        .to_proto()
        .encode_to_vec();
    let _ = spark_funcs::array_prepend(c(), c())
        .to_proto()
        .encode_to_vec();
    let _ = spark_funcs::array_remove(c(), c())
        .to_proto()
        .encode_to_vec();
    let _ = spark_funcs::array_repeat(c(), c())
        .to_proto()
        .encode_to_vec();
    let _ = spark_funcs::array_union(c(), c())
        .to_proto()
        .encode_to_vec();
    let _ = spark_funcs::arrays_overlap(c(), c())
        .to_proto()
        .encode_to_vec();
    let _ = spark_funcs::atan2(c(), c()).to_proto().encode_to_vec();
    let _ = spark_funcs::bit_get(c(), c()).to_proto().encode_to_vec();
    let _ = spark_funcs::bucket(c(), c()).to_proto().encode_to_vec();
    let _ = spark_funcs::collate(c(), c()).to_proto().encode_to_vec();
    let _ = spark_funcs::contains(c(), c()).to_proto().encode_to_vec();
    let _ = spark_funcs::corr(c(), c()).to_proto().encode_to_vec();
    let _ = spark_funcs::covar_pop(c(), c()).to_proto().encode_to_vec();
    let _ = spark_funcs::covar_samp(c(), c()).to_proto().encode_to_vec();
    let _ = spark_funcs::date_add(c(), c()).to_proto().encode_to_vec();
    let _ = spark_funcs::date_diff(c(), c()).to_proto().encode_to_vec();
    let _ = spark_funcs::date_format(c(), c())
        .to_proto()
        .encode_to_vec();
    let _ = spark_funcs::date_part(c(), c()).to_proto().encode_to_vec();
    let _ = spark_funcs::date_sub(c(), c()).to_proto().encode_to_vec();
    let _ = spark_funcs::date_trunc(c(), c()).to_proto().encode_to_vec();
    let _ = spark_funcs::dateadd(c(), c()).to_proto().encode_to_vec();
    let _ = spark_funcs::datediff(c(), c()).to_proto().encode_to_vec();
    let _ = spark_funcs::datepart(c(), c()).to_proto().encode_to_vec();
    let _ = spark_funcs::decode(c(), c()).to_proto().encode_to_vec();
    let _ = spark_funcs::element_at(c(), c()).to_proto().encode_to_vec();
    let _ = spark_funcs::encode(c(), c()).to_proto().encode_to_vec();
    let _ = spark_funcs::endswith(c(), c()).to_proto().encode_to_vec();
    let _ = spark_funcs::equal_null(c(), c()).to_proto().encode_to_vec();
    let _ = spark_funcs::extract(c(), c()).to_proto().encode_to_vec();
    let _ = spark_funcs::find_in_set(c(), c())
        .to_proto()
        .encode_to_vec();
    let _ = spark_funcs::format_number(c(), c())
        .to_proto()
        .encode_to_vec();
    let _ = spark_funcs::from_csv(c(), c()).to_proto().encode_to_vec();
    let _ = spark_funcs::from_json(c(), c()).to_proto().encode_to_vec();
    let _ = spark_funcs::from_utc_timestamp(c(), c())
        .to_proto()
        .encode_to_vec();
    let _ = spark_funcs::from_xml(c(), c()).to_proto().encode_to_vec();
    let _ = spark_funcs::get(c(), c()).to_proto().encode_to_vec();
    let _ = spark_funcs::get_json_object(c(), c())
        .to_proto()
        .encode_to_vec();
    let _ = spark_funcs::getbit(c(), c()).to_proto().encode_to_vec();
    let _ = spark_funcs::greatest(c(), c()).to_proto().encode_to_vec();
    let _ = spark_funcs::histogram_numeric(c(), c())
        .to_proto()
        .encode_to_vec();
    let _ = spark_funcs::hll_union(c(), c()).to_proto().encode_to_vec();
    let _ = spark_funcs::hypot(c(), c()).to_proto().encode_to_vec();
    let _ = spark_funcs::ifnull(c(), c()).to_proto().encode_to_vec();
    let _ = spark_funcs::ilike(c(), c()).to_proto().encode_to_vec();
    let _ = spark_funcs::instr(c(), c()).to_proto().encode_to_vec();
    let _ = spark_funcs::json_tuple(c(), c()).to_proto().encode_to_vec();
    let _ = spark_funcs::least(c(), c()).to_proto().encode_to_vec();
    let _ = spark_funcs::left(c(), c()).to_proto().encode_to_vec();
    let _ = spark_funcs::levenshtein(c(), c())
        .to_proto()
        .encode_to_vec();
    let _ = spark_funcs::like(c(), c()).to_proto().encode_to_vec();
    let _ = spark_funcs::locate(c(), c()).to_proto().encode_to_vec();
    let _ = spark_funcs::map_contains_key(c(), c())
        .to_proto()
        .encode_to_vec();
    let _ = spark_funcs::map_from_arrays(c(), c())
        .to_proto()
        .encode_to_vec();
    let _ = spark_funcs::max_by(c(), c()).to_proto().encode_to_vec();
    let _ = spark_funcs::min_by(c(), c()).to_proto().encode_to_vec();
    let _ = spark_funcs::months_between(c(), c())
        .to_proto()
        .encode_to_vec();
    let _ = spark_funcs::nanvl(c(), c()).to_proto().encode_to_vec();
    let _ = spark_funcs::next_day(c(), c()).to_proto().encode_to_vec();
    let _ = spark_funcs::nth_value(c(), c()).to_proto().encode_to_vec();
    let _ = spark_funcs::nullif(c(), c()).to_proto().encode_to_vec();
    let _ = spark_funcs::nvl(c(), c()).to_proto().encode_to_vec();
    let _ = spark_funcs::parse_url(c(), c()).to_proto().encode_to_vec();
    let _ = spark_funcs::percentile(c(), c()).to_proto().encode_to_vec();
    let _ = spark_funcs::percentile_approx(c(), c())
        .to_proto()
        .encode_to_vec();
    let _ = spark_funcs::pmod(c(), c()).to_proto().encode_to_vec();
    let _ = spark_funcs::position(c(), c()).to_proto().encode_to_vec();
    let _ = spark_funcs::pow(c(), c()).to_proto().encode_to_vec();
    let _ = spark_funcs::power(c(), c()).to_proto().encode_to_vec();
    let _ = spark_funcs::regexp(c(), c()).to_proto().encode_to_vec();
    let _ = spark_funcs::regexp_count(c(), c())
        .to_proto()
        .encode_to_vec();
    let _ = spark_funcs::regexp_extract_all(c(), c())
        .to_proto()
        .encode_to_vec();
    let _ = spark_funcs::regexp_instr(c(), c())
        .to_proto()
        .encode_to_vec();
    let _ = spark_funcs::regexp_like(c(), c())
        .to_proto()
        .encode_to_vec();
    let _ = spark_funcs::regexp_substr(c(), c())
        .to_proto()
        .encode_to_vec();
    let _ = spark_funcs::regr_avgx(c(), c()).to_proto().encode_to_vec();
    let _ = spark_funcs::regr_avgy(c(), c()).to_proto().encode_to_vec();
    let _ = spark_funcs::regr_count(c(), c()).to_proto().encode_to_vec();
    let _ = spark_funcs::regr_intercept(c(), c())
        .to_proto()
        .encode_to_vec();
    let _ = spark_funcs::regr_r2(c(), c()).to_proto().encode_to_vec();
    let _ = spark_funcs::regr_slope(c(), c()).to_proto().encode_to_vec();
    let _ = spark_funcs::regr_sxx(c(), c()).to_proto().encode_to_vec();
    let _ = spark_funcs::regr_sxy(c(), c()).to_proto().encode_to_vec();
    let _ = spark_funcs::regr_syy(c(), c()).to_proto().encode_to_vec();
    let _ = spark_funcs::repeat(c(), c()).to_proto().encode_to_vec();
    let _ = spark_funcs::replace(c(), c()).to_proto().encode_to_vec();
    let _ = spark_funcs::right(c(), c()).to_proto().encode_to_vec();
    let _ = spark_funcs::rlike(c(), c()).to_proto().encode_to_vec();
    let _ = spark_funcs::sequence(c(), c()).to_proto().encode_to_vec();
    let _ = spark_funcs::session_window(c(), c())
        .to_proto()
        .encode_to_vec();
    let _ = spark_funcs::shiftLeft(c(), c()).to_proto().encode_to_vec();
    let _ = spark_funcs::shiftRight(c(), c()).to_proto().encode_to_vec();
    let _ = spark_funcs::shiftRightUnsigned(c(), c())
        .to_proto()
        .encode_to_vec();
    let _ = spark_funcs::shiftleft(c(), c()).to_proto().encode_to_vec();
    let _ = spark_funcs::shiftright(c(), c()).to_proto().encode_to_vec();
    let _ = spark_funcs::shiftrightunsigned(c(), c())
        .to_proto()
        .encode_to_vec();
    let _ = spark_funcs::split(c(), c()).to_proto().encode_to_vec();
    let _ = spark_funcs::startswith(c(), c()).to_proto().encode_to_vec();
    let _ = spark_funcs::substr(c(), c()).to_proto().encode_to_vec();
    let _ = spark_funcs::to_char(c(), c()).to_proto().encode_to_vec();
    let _ = spark_funcs::to_number(c(), c()).to_proto().encode_to_vec();
    let _ = spark_funcs::to_utc_timestamp(c(), c())
        .to_proto()
        .encode_to_vec();
    let _ = spark_funcs::to_varchar(c(), c()).to_proto().encode_to_vec();
    let _ = spark_funcs::trunc(c(), c()).to_proto().encode_to_vec();
    let _ = spark_funcs::try_add(c(), c()).to_proto().encode_to_vec();
    let _ = spark_funcs::try_aes_decrypt(c(), c())
        .to_proto()
        .encode_to_vec();
    let _ = spark_funcs::try_divide(c(), c()).to_proto().encode_to_vec();
    let _ = spark_funcs::try_element_at(c(), c())
        .to_proto()
        .encode_to_vec();
    let _ = spark_funcs::try_mod(c(), c()).to_proto().encode_to_vec();
    let _ = spark_funcs::try_multiply(c(), c())
        .to_proto()
        .encode_to_vec();
    let _ = spark_funcs::try_parse_url(c(), c())
        .to_proto()
        .encode_to_vec();
    let _ = spark_funcs::try_subtract(c(), c())
        .to_proto()
        .encode_to_vec();
    let _ = spark_funcs::try_to_number(c(), c())
        .to_proto()
        .encode_to_vec();
    let _ = spark_funcs::uniform(c(), c()).to_proto().encode_to_vec();
    let _ = spark_funcs::when(c(), c()).to_proto().encode_to_vec();
    let _ = spark_funcs::xpath(c(), c()).to_proto().encode_to_vec();
    let _ = spark_funcs::xpath_boolean(c(), c())
        .to_proto()
        .encode_to_vec();
    let _ = spark_funcs::xpath_double(c(), c())
        .to_proto()
        .encode_to_vec();
    let _ = spark_funcs::xpath_float(c(), c())
        .to_proto()
        .encode_to_vec();
    let _ = spark_funcs::xpath_int(c(), c()).to_proto().encode_to_vec();
    let _ = spark_funcs::xpath_long(c(), c()).to_proto().encode_to_vec();
    let _ = spark_funcs::xpath_number(c(), c())
        .to_proto()
        .encode_to_vec();
    let _ = spark_funcs::xpath_short(c(), c())
        .to_proto()
        .encode_to_vec();
    let _ = spark_funcs::xpath_string(c(), c())
        .to_proto()
        .encode_to_vec();
    let _ = spark_funcs::array_insert(c(), c(), c())
        .to_proto()
        .encode_to_vec();
    let _ = spark_funcs::conv(c(), c(), c()).to_proto().encode_to_vec();
    let _ = spark_funcs::convert_timezone(c(), c(), c())
        .to_proto()
        .encode_to_vec();
    let _ = spark_funcs::count_min_sketch(c(), c(), c())
        .to_proto()
        .encode_to_vec();
    let _ = spark_funcs::lpad(c(), c(), c()).to_proto().encode_to_vec();
    let _ = spark_funcs::make_date(c(), c(), c())
        .to_proto()
        .encode_to_vec();
    let _ = spark_funcs::nvl2(c(), c(), c()).to_proto().encode_to_vec();
    let _ = spark_funcs::overlay(c(), c(), c())
        .to_proto()
        .encode_to_vec();
    let _ = spark_funcs::regexp_extract(c(), c(), c())
        .to_proto()
        .encode_to_vec();
    let _ = spark_funcs::regexp_replace(c(), c(), c())
        .to_proto()
        .encode_to_vec();
    let _ = spark_funcs::rpad(c(), c(), c()).to_proto().encode_to_vec();
    let _ = spark_funcs::slice(c(), c(), c()).to_proto().encode_to_vec();
    let _ = spark_funcs::split_part(c(), c(), c())
        .to_proto()
        .encode_to_vec();
    let _ = spark_funcs::substring(c(), c(), c())
        .to_proto()
        .encode_to_vec();
    let _ = spark_funcs::substring_index(c(), c(), c())
        .to_proto()
        .encode_to_vec();
    let _ = spark_funcs::timestamp_add(c(), c(), c())
        .to_proto()
        .encode_to_vec();
    let _ = spark_funcs::timestamp_diff(c(), c(), c())
        .to_proto()
        .encode_to_vec();
    let _ = spark_funcs::translate(c(), c(), c())
        .to_proto()
        .encode_to_vec();
    let _ = spark_funcs::try_variant_get(c(), c(), c())
        .to_proto()
        .encode_to_vec();
    let _ = spark_funcs::variant_get(c(), c(), c())
        .to_proto()
        .encode_to_vec();
    let _ = spark_funcs::width_bucket(c(), c(), c(), c())
        .to_proto()
        .encode_to_vec();
    let _ = spark_funcs::from_protobuf(c(), "x")
        .to_proto()
        .encode_to_vec();
    let _ = spark_funcs::from_protobuf_with_options(c(), "x", c())
        .to_proto()
        .encode_to_vec();
    let _ = spark_funcs::to_protobuf(c(), "x")
        .to_proto()
        .encode_to_vec();
    let _ = spark_funcs::to_protobuf_with_options(c(), "x", c())
        .to_proto()
        .encode_to_vec();
    let _ = spark_funcs::from_avro(c(), "x").to_proto().encode_to_vec();
    let _ = spark_funcs::from_avro_with_options(c(), "x", c())
        .to_proto()
        .encode_to_vec();
    let _ = spark_funcs::to_avro(c()).to_proto().encode_to_vec();
    let _ = spark_funcs::to_avro_with_schema(c(), "x")
        .to_proto()
        .encode_to_vec();
    let _ = spark_funcs::bitmap_and_agg(c()).to_proto().encode_to_vec();
    let _ = spark_funcs::chr(c()).to_proto().encode_to_vec();
    let _ = spark_funcs::counter_diff(c()).to_proto().encode_to_vec();
    let _ = spark_funcs::current_path().to_proto().encode_to_vec();
    let _ = spark_funcs::current_time().to_proto().encode_to_vec();
    let _ = spark_funcs::hmac(c(), c()).to_proto().encode_to_vec();
    let _ = spark_funcs::is_valid_variant(c())
        .to_proto()
        .encode_to_vec();
    let _ = spark_funcs::jaro_winkler_similarity(c(), c())
        .to_proto()
        .encode_to_vec();
    let _ = spark_funcs::kll_merge_agg_bigint(c())
        .to_proto()
        .encode_to_vec();
    let _ = spark_funcs::kll_merge_agg_double(c())
        .to_proto()
        .encode_to_vec();
    let _ = spark_funcs::kll_merge_agg_float(c())
        .to_proto()
        .encode_to_vec();
    let _ = spark_funcs::kll_sketch_agg_bigint(c())
        .to_proto()
        .encode_to_vec();
    let _ = spark_funcs::kll_sketch_agg_double(c())
        .to_proto()
        .encode_to_vec();
    let _ = spark_funcs::kll_sketch_agg_float(c())
        .to_proto()
        .encode_to_vec();
    let _ = spark_funcs::kll_sketch_get_n_bigint(c())
        .to_proto()
        .encode_to_vec();
    let _ = spark_funcs::kll_sketch_get_n_double(c())
        .to_proto()
        .encode_to_vec();
    let _ = spark_funcs::kll_sketch_get_n_float(c())
        .to_proto()
        .encode_to_vec();
    let _ = spark_funcs::kll_sketch_get_quantile_bigint(c(), c())
        .to_proto()
        .encode_to_vec();
    let _ = spark_funcs::kll_sketch_get_quantile_double(c(), c())
        .to_proto()
        .encode_to_vec();
    let _ = spark_funcs::kll_sketch_get_quantile_float(c(), c())
        .to_proto()
        .encode_to_vec();
    let _ = spark_funcs::kll_sketch_get_rank_bigint(c(), c())
        .to_proto()
        .encode_to_vec();
    let _ = spark_funcs::kll_sketch_get_rank_double(c(), c())
        .to_proto()
        .encode_to_vec();
    let _ = spark_funcs::kll_sketch_get_rank_float(c(), c())
        .to_proto()
        .encode_to_vec();
    let _ = spark_funcs::kll_sketch_merge_bigint(c(), c())
        .to_proto()
        .encode_to_vec();
    let _ = spark_funcs::kll_sketch_merge_double(c(), c())
        .to_proto()
        .encode_to_vec();
    let _ = spark_funcs::kll_sketch_merge_float(c(), c())
        .to_proto()
        .encode_to_vec();
    let _ = spark_funcs::kll_sketch_to_string_bigint(c())
        .to_proto()
        .encode_to_vec();
    let _ = spark_funcs::kll_sketch_to_string_double(c())
        .to_proto()
        .encode_to_vec();
    let _ = spark_funcs::kll_sketch_to_string_float(c())
        .to_proto()
        .encode_to_vec();
    let _ = spark_funcs::make_time(c(), c(), c())
        .to_proto()
        .encode_to_vec();
    let _ = spark_funcs::make_timestamp(c(), c(), c(), c(), c(), c())
        .to_proto()
        .encode_to_vec();
    let _ = spark_funcs::make_timestamp_ltz(c(), c(), c(), c(), c(), c())
        .to_proto()
        .encode_to_vec();
    let _ = spark_funcs::make_timestamp_ntz(c(), c(), c(), c(), c(), c())
        .to_proto()
        .encode_to_vec();
    let _ = spark_funcs::quote(c()).to_proto().encode_to_vec();
    let _ = spark_funcs::sha2(c(), 2).to_proto().encode_to_vec();
    let _ = spark_funcs::st_asbinary(c()).to_proto().encode_to_vec();
    let _ = spark_funcs::st_geogfromwkb(c()).to_proto().encode_to_vec();
    let _ = spark_funcs::st_geomfromwkb(c()).to_proto().encode_to_vec();
    let _ = spark_funcs::st_setsrid(c(), c()).to_proto().encode_to_vec();
    let _ = spark_funcs::st_srid(c()).to_proto().encode_to_vec();
    let _ = spark_funcs::theta_difference(c(), c())
        .to_proto()
        .encode_to_vec();
    let _ = spark_funcs::theta_intersection(c(), c())
        .to_proto()
        .encode_to_vec();
    let _ = spark_funcs::theta_intersection_agg(c())
        .to_proto()
        .encode_to_vec();
    let _ = spark_funcs::theta_sketch_agg(c())
        .to_proto()
        .encode_to_vec();
    let _ = spark_funcs::theta_sketch_estimate(c())
        .to_proto()
        .encode_to_vec();
    let _ = spark_funcs::theta_union(c(), c())
        .to_proto()
        .encode_to_vec();
    let _ = spark_funcs::theta_union_agg(c()).to_proto().encode_to_vec();
    let _ = spark_funcs::time_bucket(c(), c())
        .to_proto()
        .encode_to_vec();
    let _ = spark_funcs::time_diff(c(), c(), c())
        .to_proto()
        .encode_to_vec();
    let _ = spark_funcs::time_from_micros(c())
        .to_proto()
        .encode_to_vec();
    let _ = spark_funcs::time_from_millis(c())
        .to_proto()
        .encode_to_vec();
    let _ = spark_funcs::time_from_seconds(c())
        .to_proto()
        .encode_to_vec();
    let _ = spark_funcs::time_to_micros(c()).to_proto().encode_to_vec();
    let _ = spark_funcs::time_to_millis(c()).to_proto().encode_to_vec();
    let _ = spark_funcs::time_to_seconds(c()).to_proto().encode_to_vec();
    let _ = spark_funcs::time_trunc(c(), c()).to_proto().encode_to_vec();
    let _ = spark_funcs::timestamp_nanos(c()).to_proto().encode_to_vec();
    let _ = spark_funcs::to_time(c()).to_proto().encode_to_vec();
    let _ = spark_funcs::try_make_timestamp(c(), c(), c(), c(), c(), c())
        .to_proto()
        .encode_to_vec();
    let _ = spark_funcs::try_make_timestamp_ltz(c(), c(), c(), c(), c(), c())
        .to_proto()
        .encode_to_vec();
    let _ = spark_funcs::try_make_timestamp_ntz(c(), c(), c(), c(), c(), c())
        .to_proto()
        .encode_to_vec();
    let _ = spark_funcs::try_to_date(c()).to_proto().encode_to_vec();
    let _ = spark_funcs::try_to_time(c()).to_proto().encode_to_vec();
    let _ = spark_funcs::try_variant_array_append(c(), c(), c())
        .to_proto()
        .encode_to_vec();
    let _ = spark_funcs::try_variant_insert(c(), c(), c())
        .to_proto()
        .encode_to_vec();
    let _ = spark_funcs::try_variant_set(c(), c(), c())
        .to_proto()
        .encode_to_vec();
    let _ = spark_funcs::unix_nanos(c()).to_proto().encode_to_vec();
    let _ = spark_funcs::uuid().to_proto().encode_to_vec();
    let _ = spark_funcs::variant_array_append(c(), c(), c())
        .to_proto()
        .encode_to_vec();
    let _ = spark_funcs::variant_delete(c(), vec![c(), c()])
        .to_proto()
        .encode_to_vec();
    let _ = spark_funcs::variant_insert(c(), c(), c())
        .to_proto()
        .encode_to_vec();
    let _ = spark_funcs::variant_set(c(), c(), c())
        .to_proto()
        .encode_to_vec();
    let _ = spark_funcs::vector_avg(c()).to_proto().encode_to_vec();
    let _ = spark_funcs::vector_cosine_similarity(c(), c())
        .to_proto()
        .encode_to_vec();
    let _ = spark_funcs::vector_inner_product(c(), c())
        .to_proto()
        .encode_to_vec();
    let _ = spark_funcs::vector_l2_distance(c(), c())
        .to_proto()
        .encode_to_vec();
    let _ = spark_funcs::vector_norm(c()).to_proto().encode_to_vec();
    let _ = spark_funcs::vector_normalize(c())
        .to_proto()
        .encode_to_vec();
    let _ = spark_funcs::vector_sum(c()).to_proto().encode_to_vec();
    let _ = spark_funcs::tuple_difference_double(c(), c())
        .to_proto()
        .encode_to_vec();
    let _ = spark_funcs::tuple_difference_integer(c(), c())
        .to_proto()
        .encode_to_vec();
    let _ = spark_funcs::tuple_difference_theta_double(c(), c())
        .to_proto()
        .encode_to_vec();
    let _ = spark_funcs::tuple_difference_theta_integer(c(), c())
        .to_proto()
        .encode_to_vec();
    let _ = spark_funcs::tuple_intersection_agg_double(c())
        .to_proto()
        .encode_to_vec();
    let _ = spark_funcs::tuple_intersection_agg_integer(c())
        .to_proto()
        .encode_to_vec();
    let _ = spark_funcs::tuple_intersection_double(c(), c())
        .to_proto()
        .encode_to_vec();
    let _ = spark_funcs::tuple_intersection_integer(c(), c())
        .to_proto()
        .encode_to_vec();
    let _ = spark_funcs::tuple_intersection_theta_double(c(), c())
        .to_proto()
        .encode_to_vec();
    let _ = spark_funcs::tuple_intersection_theta_integer(c(), c())
        .to_proto()
        .encode_to_vec();
    let _ = spark_funcs::tuple_sketch_agg_double(c(), c())
        .to_proto()
        .encode_to_vec();
    let _ = spark_funcs::tuple_sketch_agg_integer(c(), c())
        .to_proto()
        .encode_to_vec();
    let _ = spark_funcs::tuple_sketch_estimate_double(c())
        .to_proto()
        .encode_to_vec();
    let _ = spark_funcs::tuple_sketch_estimate_integer(c())
        .to_proto()
        .encode_to_vec();
    let _ = spark_funcs::tuple_sketch_summary_double(c())
        .to_proto()
        .encode_to_vec();
    let _ = spark_funcs::tuple_sketch_summary_integer(c())
        .to_proto()
        .encode_to_vec();
    let _ = spark_funcs::tuple_sketch_theta_double(c())
        .to_proto()
        .encode_to_vec();
    let _ = spark_funcs::tuple_sketch_theta_integer(c())
        .to_proto()
        .encode_to_vec();
    let _ = spark_funcs::tuple_union_agg_double(c())
        .to_proto()
        .encode_to_vec();
    let _ = spark_funcs::tuple_union_agg_integer(c())
        .to_proto()
        .encode_to_vec();
    let _ = spark_funcs::tuple_union_double(c(), c())
        .to_proto()
        .encode_to_vec();
    let _ = spark_funcs::tuple_union_integer(c(), c())
        .to_proto()
        .encode_to_vec();
    let _ = spark_funcs::tuple_union_theta_double(c(), c())
        .to_proto()
        .encode_to_vec();
    let _ = spark_funcs::tuple_union_theta_integer(c(), c())
        .to_proto()
        .encode_to_vec();
}
