// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

//! Single-file Rust UDF on Spark: define the functions and use them in one file.
//!
//! `build.rs` compiles this same file to a `wasm32` module (host-only code is
//! `#[cfg(not(target_arch = "wasm32"))]`, so only the exported UDFs survive) and
//! embeds it; `#[spark_wasm_udf]` generates the `udf::*()` constructors.
//!
//! Run (needs the wasm32 target + a Spark Connect server, `wasmtime` on the
//! executors):
//!
//!     rustup target add wasm32-unknown-unknown
//!     export SPARK_CONNECT_WASM_PACKER_PATH=$PWD/python
//!     cargo run -p wasm-udf-inline

use spark_connect_macros::spark_wasm_udf;

/// The UDFs — plain Rust functions. That's all the user writes.
#[spark_wasm_udf]
mod udfs {
    pub fn add_one(x: i64) -> i64 {
        x + 1
    }

    pub fn shout(s: String) -> String {
        format!("{}!", s.to_uppercase())
    }
}

#[cfg(not(target_arch = "wasm32"))]
fn main() -> Result<(), Box<dyn std::error::Error>> {
    use spark_connect::functions::col;
    use spark_connect::{SparkSession, SparkSessionBuilder};

    let spark: SparkSession = SparkSessionBuilder::default()
        .remote("sc://127.0.0.1:15002/")
        .get_or_create()?;

    // `udf::*` constructors are generated by the macro: signatures inferred,
    // module embedded. Pass columns straight in (one per argument) -- no wasm
    // bytes or signature to write by hand.
    spark
        .range(5)?
        .select([
            col("id"),
            udf::add_one(col("id"))?.alias("id_plus_one"),
            udf::shout(col("id").cast(spark_connect::types::DataType::String {
                collation: "UTF8_BINARY".to_string(),
            }))?
            .alias("shouted"),
        ])
        .show(20)?;

    Ok(())
}
