// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// The "just write a Rust function and run it" example.
//
// The UDFs are defined in the `wasm-udfs` crate as plain functions annotated
// with `#[spark_wasm_udf]` -- e.g.
//
//     #[spark_wasm_udf]
//     pub fn add_one(x: i64) -> i64 { x + 1 }
//
// The macro infers the signature and generates `add_one_udf(module)`. This
// crate's `build.rs` compiles `wasm-udfs` to WebAssembly and embeds it, so
// there is no manual wasm build or file loading.
//
// Run with (needs the wasm32 target + a Spark Connect server, and `wasmtime`
// on the executors):
//
//     rustup target add wasm32-unknown-unknown
//     export SPARK_CONNECT_WASM_PACKER_PATH=$PWD/python
//     cargo run -p examples --bin wasm_udf_macro --features wasm-udf-macro

use spark_connect::functions::col;
use spark_connect::{SparkSession, SparkSessionBuilder};

/// The compiled `wasm-udfs` module, embedded at build time by `build.rs`.
static WASM_MODULE: &[u8] = include_bytes!(env!("WASM_UDFS_MODULE"));

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let spark: SparkSession = SparkSessionBuilder::default()
        .remote("sc://127.0.0.1:15002/")
        .get_or_create()?;

    // `*_udf` constructors are generated by `#[spark_wasm_udf]`, with Spark
    // types inferred from each Rust signature. Only the module bytes are passed.
    let add_one = wasm_udfs::add_one_udf(WASM_MODULE);
    let c2f = wasm_udfs::celsius_to_fahrenheit_udf(WASM_MODULE);
    let gcd = wasm_udfs::gcd_udf(WASM_MODULE);

    let df = spark.range(5)?;

    df.select(vec![
        col("id"),
        add_one.call(vec![col("id")])?.alias("id_plus_one"),
        c2f.call(vec![col("id").cast(spark_connect::types::DataType::Double)])?
            .alias("as_fahrenheit"),
        gcd.call(vec![col("id"), spark_connect::lit(12)])?
            .alias("gcd_with_12"),
    ])
    .show(20)?;

    Ok(())
}
