#!/usr/bin/env python3
"""Generate a coverage smoke test that constructs *every* `functions.*` builder.

Unlike `tests/functions_golden.rs` (byte-for-byte parity against a captured
reference set, whose case list is hand-maintained and lags new functions), this
parses `crates/spark-connect/src/functions.rs` and emits one call per public
builder with canonical arguments, then serializes each to protobuf. Its purpose
is purely to exercise every builder body (and the closures they invoke) so the
coverage gate sees them; correctness is covered by the parity golden.

Regenerate after adding/removing functions:

    python scripts/gen_functions_coverage_test.py
"""

import re
from pathlib import Path

SRC = Path("crates/spark-connect/src/functions.rs")
OUT = Path("crates/spark-connect/tests/functions_coverage_golden.rs")

# Builders whose signatures don't take the canonical (Column | &str | Vec<Column>
# | i32) args, or that need a live DataFrame/session — exercised elsewhere.
SKIP = {
    "broadcast",  # broadcast(DataFrame) -> Column: needs a real DataFrame
}


def arg_for(ptype: str) -> str:
    """Canonical argument expression for a parameter of the given Rust type."""
    t = ptype.strip()
    if "Vec<Column>" in t:
        return "vec![c(), c()]"
    if "Column" in t:
        return "c()"
    if "&str" in t or t == "str":
        return '"x"'
    if t in ("i32", "i64", "u32", "u64", "usize", "isize"):
        return "2"
    if t in ("f32", "f64"):
        return "2.0"
    if t == "bool":
        return "true"
    return None  # signals: skip this function


def parse_functions(text: str):
    pattern = r"^pub fn ([a-zA-Z0-9_#]+)\((.*?)\)\s*->\s*Column\s*\{"
    for m in re.finditer(pattern, text, re.MULTILINE | re.DOTALL):
        full_name = m.group(1)
        params_str = m.group(2).strip()
        params = []
        if params_str:
            # split on top-level commas (angle brackets can nest, e.g. Vec<Column>)
            depth, cur = 0, ""
            parts = []
            for ch in params_str:
                if ch == "<":
                    depth += 1
                elif ch == ">":
                    depth -= 1
                elif ch == "," and depth == 0:
                    parts.append(cur.strip())
                    cur = ""
                    continue
                cur += ch
            if cur.strip():
                parts.append(cur.strip())
            for p in parts:
                if ":" in p:
                    params.append(p.split(":", 1)[1].strip())
        yield full_name, params


def main():
    text = SRC.read_text()
    calls = []
    skipped = []
    for full_name, ptypes in parse_functions(text):
        name = full_name.replace("r#", "")
        if name in SKIP:
            skipped.append(name)
            continue
        args = [arg_for(t) for t in ptypes]
        if any(a is None for a in args):
            skipped.append(name)
            continue
        calls.append(
            f"        let _ = spark_funcs::{full_name}({', '.join(args)}).to_proto().encode_to_vec();"
        )

    body = "\n".join(calls)
    out = f"""//! Auto-generated coverage smoke test - do not edit directly.
//! Generated by scripts/gen_functions_coverage_test.py.
//!
//! Constructs every public `functions.*` builder with canonical arguments and
//! serializes it to protobuf, so the coverage gate exercises every builder body.
//! Correctness/parity is covered by `functions_golden.rs`; this only guards that
//! no builder panics or is left untested. {len(calls)} builders exercised;
//! {len(skipped)} skipped (non-canonical signatures): {", ".join(sorted(skipped))}.

use prost::Message;
use spark_connect::column::Column;
use spark_connect::expression::{{ColumnReference, Expression}};
use spark_connect::functions as spark_funcs;

/// A canonical column reference argument.
fn c() -> Column {{
    Column::new(Expression::ColumnReference(ColumnReference::new("c")))
}}

#[test]
fn every_function_builder_serializes() {{
{body}
}}
"""
    OUT.write_text(out)
    print(f"Wrote {OUT}: {len(calls)} builders, {len(skipped)} skipped")


if __name__ == "__main__":
    main()
